implement 1st year/02 Roots of quadratic equation python solution
atarax665/VTU-Lab-Programs pull request #13
Opened 2020-10-31 15:39 UTC by VickyGuo0907

### Have you read the [Contributing Guidelines on Pull Requests]()?

- [X] Yes

### Description

(Write your answer here.)

### Checklist

- [X] I've read the contribution guidelines.
- [X] This PR meets all the requirements like Clean Code, proper README and Documentation.

### Related Issues or Pull Requests

Fixes: #5 

### Screenshots (if any)

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot**|

2020-10-31 17:52 UTC, atarax665 requested changes

2020-10-31 17:52 UTC, atarax665 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +  print("some test cases:")
No need to add this sample test cases.

2020-10-31 17:52 UTC, atarax665 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +    r1 = r2 = -b / (2 * a)
```suggestion
    r1 = r2 = - b / (2 * a)
```

2020-10-31 17:52 UTC, atarax665 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +    r2 = (-b - sql_val)/(2 * a)
```suggestion
    r2 = (- b - sql_val) / (2 * a)
```

2020-10-31 17:52 UTC, atarax665 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +    r1 = (-b + sql_val)/(2 * a)
```suggestion
    r1 = (- b + sql_val) / (2 * a)
```

2020-10-31 17:52 UTC, atarax665 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +    r = -b/(2 * a)
```suggestion
    r = - b / (2 * a)
```

2020-10-31 17:52 UTC, atarax665 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +
Remove these extra line breaks.

2020-10-31 19:16 UTC, VickyGuo0907 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +  print("some test cases:")
removed

2020-10-31 19:16 UTC, VickyGuo0907 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +    r1 = r2 = -b / (2 * a)
resolved

2020-10-31 19:17 UTC, VickyGuo0907 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +    r1 = (-b + sql_val)/(2 * a)
resoved

2020-10-31 19:18 UTC, VickyGuo0907 commented on 1st Year/02. Roots of a quadratic equation/quadratic.py
> +
solved

2020-11-02 18:14 UTC, atarax665 approved these changes
:+1: :+1:

2020-11-02 18:14 UTC, merged